# Generated by Django 2.0.7 on 2018-07-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type_of_user',
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('staff', 'Staff'), ('student', 'Student'), ('superadmin', 'Super Admin')], default='staff', max_length=11),
            preserve_default=False,
        ),
    ]
