# Generated by Django 2.1 on 2018-08-09 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180802_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='duration',
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=20, seconds=36000)),
        ),
    ]
