# Generated by Django 2.0.7 on 2018-07-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180726_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionModel',
            new_name='Option',
        ),
    ]
