# Generated by Django 2.1.4 on 2018-12-21 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181221_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 11, 36, 49, 991971, tzinfo=utc)),
        ),
    ]
