# Generated by Django 2.1.4 on 2018-12-26 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181221_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ManyToManyField(blank=True, to='api.Course'),
        ),
        migrations.AlterField(
            model_name='test',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
