# Generated by Django 2.0.7 on 2018-07-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180725_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
