# Generated by Django 2.1.4 on 2018-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181226_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='typeOfTest',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('practice', 'practice')], default='practice', max_length=8),
            preserve_default=False,
        ),
    ]
