# Generated by Django 2.0.7 on 2018-07-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180727_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='super_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SuperAdmin'),
        ),
    ]
