# Generated by Django 2.0.7 on 2018-07-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180727_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.IntegerField(default=9578473849),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='profileimgs/'),
        ),
    ]
