# Generated by Django 2.1.4 on 2019-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bulkstudentscsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkstudentscsv',
            name='number',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
