# Generated by Django 2.0.7 on 2018-07-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180727_2307'),
        ('api', '0006_auto_20180726_1329'),
    ]

    operations = [
    ]
