# Generated by Django 2.0.7 on 2018-07-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180726_1329'),
        ('api', '0011_auto_20180727_2307'),
    ]

    operations = [
    ]
