# Generated by Django 2.1.4 on 2019-01-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bulkstudentscsv_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ManyToManyField(to='api.Course'),
        ),
    ]
