# Generated by Django 2.0.7 on 2018-07-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20180727_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Centre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Centre'),
            preserve_default=False,
        ),
    ]
