# Generated by Django 2.0.7 on 2018-07-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180727_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Someone', max_length=50),
            preserve_default=False,
        ),
    ]
