# Generated by Django 2.0.7 on 2018-07-30 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180728_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Centre'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='super_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Centre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='profileimgs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='super_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='institution_name',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
