# Generated by Django 2.0.7 on 2018-07-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180728_0212'),
        ('api', '0012_merge_20180728_0928'),
    ]

    operations = [
    ]
