# Generated by Django 2.1.4 on 2019-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_question_quesnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quesNumber',
            field=models.IntegerField(default=1),
        ),
    ]
