# Generated by Django 2.0.7 on 2018-07-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180730_0308'),
        ('api', '0017_auto_20180730_0210'),
    ]

    operations = [
    ]
