# Generated by Django 2.1.4 on 2019-01-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190118_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='section',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.Section'),
            preserve_default=False,
        ),
    ]
