# Generated by Django 2.0.7 on 2018-07-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20180730_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='super_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SuperAdmin'),
        ),
    ]
