# Generated by Django 2.1.4 on 2019-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_test_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sectionNumber',
            field=models.IntegerField(default=1),
        ),
    ]
