# Generated by Django 2.1.4 on 2019-01-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_section_sectionnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='marksPostive',
            new_name='marksPositive',
        ),
    ]
