# Generated by Django 2.1.4 on 2019-01-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190121_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionwiseresponse',
            name='userChoices',
            field=models.ManyToManyField(blank=True, to='api.Option'),
        ),
    ]
