# Generated by Django 2.1.4 on 2019-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_test_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkstudentscsv',
            name='endAccessDate',
            field=models.DateField(default='2020-04-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='endAccessDate',
            field=models.DateField(default='2020-04-01'),
            preserve_default=False,
        ),
    ]
