# Generated by Django 2.1.4 on 2019-02-15 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_student_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joiningDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
