# Generated by Django 2.1.4 on 2019-02-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190215_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid',
            field=models.BooleanField(default=0),
        ),
    ]
